### ISSUE TITLE
Cannot remove apps

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#688] opened 2024-06-21 01:30 UTC
I went to uninstall some programs and i gave me an error. It seems the remove script is not formatted properly.

Example:
nvtop
```
#!/bin/sh
rm -R -f /home/geo/.local/share/applications/AM-nvtop.desktop /home/geo/Applications/nvtop /home/geo/.local/bin/nvtop
```

cpufetch
`#!/bin/sh\nset -e\nrm -f /home/geo/.local/bin/cpufetch\nrm -R -f /home/geo/Applications/cpufetch`

**Comment by Samueru-sama** [comment] 2024-06-21 01:35
What error did you get? 

Also is nvtop or cpufetch that has the problem?

**Comment by GeoBoi254** [comment] 2024-06-21 01:37
> What error did you get?
> 
> Also is nvtop or cpufetch that has the problem?

nvtop uninstalls properly but cpufetch doesnt
Heres the error
`/home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/cpufetch/remove: cannot execute: required file not found`

**Comment by ivan-hc** [comment] 2024-06-21 01:40
> cpufetch `#!/bin/sh\nset -e\nrm -f /home/geo/.local/bin/cpufetch\nrm -R -f /home/geo/Applications/cpufetch`

I've installed it before I've uploaded it, with AppMan... strange

**Comment by Samueru-sama** [comment] 2024-06-21 01:40
Oh I see the problem now. 

`#!/bin/sh\nset -e\nrm -f /home/geo/.local/bin/cpufetch\nrm -R -f /home/geo/Applications/cpufetch`

This will create a remove file that should look like this: 

```
#!/bin/sh
set -e
/home/geo/.local/bin/cpufetch
rm -R -f /home/geo/Applications/cpufetch

```

Very likely there is something wrong in the install script that caused `/home/geo/.local/bin/cpufetch` to not be created. As result the remover will not continue, that's intended.

**Comment by ivan-hc** [comment] 2024-06-21 01:43
I cannot reproduce the issue

![Istantanea_2024-06-21_03-42-17 png](https://github.com/ivan-hc/AM/assets/88724353/36a3aa82-dbd2-4999-a990-87c6827c21f4)

**Comment by GeoBoi254** [comment] 2024-06-21 01:46
@ivan-hc try removing it

**Comment by Samueru-sama** [comment] 2024-06-21 01:47
Just tested the script as well: 

![image](https://github.com/ivan-hc/AM/assets/36420837/5acc19d3-3506-47aa-9a6c-bcf5ca4d65ea)

@GeoBoi254 Very likely for some reason you are missing the cpufetch symlink in ~/.local/bin. 

Can you post the output of `cat ~/Applications/cpufetch/remove` ?

**Comment by ivan-hc** [comment] 2024-06-21 01:48
> @ivan-hc try removing it

done, no issues here. Its very strange.

**Comment by GeoBoi254** [comment] 2024-06-21 01:52
> Can you post the output of `cat ~/Applications/cpufetch/remove` ?

```
cat ~/Applications/cpufetch/remove
#!/bin/sh\nset -e\nrm -f /home/geo/.local/bin/cpufetch\nrm -R -f /home/geo/Applications/cpufetch
```

**Comment by Samueru-sama** [comment] 2024-06-21 01:52
**Ok something went very very wrong here.**

Do you have this issue with other applications that were recently added?

**Comment by ivan-hc** [comment] 2024-06-21 01:54
@Samueru-sama may this in issue with the SHELL?

**Comment by Samueru-sama** [comment] 2024-06-21 01:55
> @Samueru-sama may this in issue with the SHELL?

If that's the case then all other scripts that use this remover also have the issue. 

I'm waiting for @GeoBoi254 to reply.

**Comment by GeoBoi254** [comment] 2024-06-21 01:57
> **Ok something went very very wrong here.**
> 
> Do you have this issue with other applications that were recently added?

```
appman -R tlock bottom onefetch
/home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/tlock/remove: cannot execute: required file not found
/home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/bottom/remove: cannot execute: required file not found
/home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/onefetch/remove: cannot execute: required file not found

```

**Comment by Samueru-sama** [comment] 2024-06-21 01:58
> > **Ok something went very very wrong here.**
> > Do you have this issue with other applications that were recently added?
> 
> ```
> appman -R tlock bottom onefetch
> /home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/tlock/remove: cannot execute: required file not found
> /home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/bottom/remove: cannot execute: required file not found
> /home/geo/Applications/appman/modules/management.am: line 36: /home/geo/Applications/onefetch/remove: cannot execute: required file not found
> ```

What's the output of `readlink /bin/sh`?

**Comment by GeoBoi254** [comment] 2024-06-21 02:00
> What's the output of readlink /bin/sh?

```
readlink /bin/sh
bash
```

**Comment by Samueru-sama** [comment] 2024-06-21 02:05
> > What's the output of readlink /bin/sh?
> 
> ```
> readlink /bin/sh
> bash
> ```

Ok in the meantime you can install dash (are you using archlinux?) if that is the case use this aur package: https://aur.archlinux.org/packages/dashbinsh

This will fix the issue for new packages you install while I fix this. 

@ivan-hc I just replicated the issue, when bash is the sh it doesn't expand the echo. I will fix this asap.

**Comment by Samueru-sama** [comment] 2024-06-21 02:09
@ivan-hc You were right it is that darm echo. 

changing to `printf` fixes the issue. So I just need to run a single sed on the database to fix this.

**Comment by ivan-hc** [comment] 2024-06-21 02:11
> So I just need to run a single sed on the database to fix this.

???

**Comment by Samueru-sama** [comment] 2024-06-21 02:19
> > So I just need to run a single sed on the database to fix this.
> 
> ???

This fixes the issue quickly: 

![image](https://github.com/ivan-hc/AM/assets/36420837/04b499f8-5370-4902-bca0-2c4ac88b7a29)

I'm going to test it with both bash and dash, then download the database, filter the scripts with `AM INSTALL SCRIPT VERSION 3.` and apply the fix.

**Comment by ivan-hc** [comment] 2024-06-21 02:24
@Samueru-sama  this way you patch all installation scripts with a `echo "#!/bin/sh`, stop it

**Comment by ivan-hc** [comment] 2024-06-21 02:26
use the patch only against your templates

**Comment by ivan-hc** [comment] 2024-06-21 02:30
`echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"`

**Comment by Samueru-sama** [comment] 2024-06-21 02:35
I modified the sed to this: 

`sed -i 's|echo "#!/bin/sh|printf "#!/bin/sh|g; s|echo "rm -f|printf '\''\\n%s'\'' "rm -f|g' `

Because it turns out that if I don't add the `\n%s` to the next prinft, it still adds the next append to the existing line. 

>use the patch only against your templates

Yeah those are the scripts that have `AM INSTALL SCRIPT VERSION 3.` written in them

**Comment by Samueru-sama** [comment] 2024-06-21 02:43
![image](https://github.com/ivan-hc/AM/assets/36420837/5b304ff6-5428-4cb9-8948-9bbd71c1d221)

69 scripts needed the fix. (It had to be that number lmao).

**Comment by ivan-hc** [comment] 2024-06-21 02:51
This is the same for the templates.

Merge in dev, push in "dev", we are almost ready for the new release.

**Comment by Samueru-sama** [comment] 2024-06-21 04:52
@GeoBoi254 The issue should be fixed now. 

Please manually remove the directories of the applications that failed and try again and let me know. 

If you installed the aur package remove it and make sure that bash is your sh by doing `readlink /bin/sh` again.

**Comment by Samueru-sama** [comment] 2024-06-21 05:37
@GeoBoi254 Did it work? I noticed voted the comment. 

We have to be sure that you can remove `cpufetch` after installing it again. 

That remove the cpufetch directory from `~/Applications`, then reinstall and remove with am/appman.

**Comment by GeoBoi254** [comment] 2024-06-21 06:20
> @GeoBoi254 Did it work? I noticed voted the comment.
> 
> We have to be sure that you can remove `cpufetch` after installing it again.
> 
> That is remove the cpufetch directory from `~/Applications`, then reinstall and remove with am/appman. (And make sure that `readlink /bin/sh` says bash before doing that)

appman -R cpufetch
 ◆ "CPUFETCH" HAS BEEN SUCCESSFULLY REMOVED!

**Comment by Samueru-sama** [comment] 2024-06-21 19:04
@ivan-hc Hey this can be closed now

**Closed** 2024-06-21 19:06 UTC
