### ISSUE TITLE
music assistant

### ISSUE THREAD

**Issue by skyw33** [ivan-hc/AM#796] opened 2024-07-27 12:42 UTC
I'm trying to add the music assistant appimage, but getting a generic error:

```
am -e https://github.com/music-assistant/companion music.assistant.companion
[sudo] password for jon: 
############################################################################
##                                                                        ##
##                  START OF ALL INSTALLATION PROCESSES                   ##
##                                                                        ##
############################################################################

◆ "MUSIC.ASSISTANT.COMPANION": starting installation script


 💀 ERROR DURING INSTALLATION, REMOVED "MUSIC.ASSISTANT.COMPANION"!
```

**Comment by Samueru-sama** [comment] 2024-07-27 13:01
HI I just made the [PR](https://github.com/ivan-hc/AM/pull/797) adding the the application to the internal database of am.

Once merged you will be able to install the application with `am -i music-assistant-companion` or `appman -i music-assistant-companion` if you would like to have the appimage in your home dir.

Btw during testing I noticed that I had a broken .desktop file, that's because the appimage has a broken link for .desktop inside of it, I will report this later to the music assistant folks, I worked around the issue in the installation script anyway.

**Comment by ivan-hc** [comment] 2024-07-27 13:54
just added https://github.com/ivan-hc/AM/pull/797 thanks @Samueru-sama

**Comment by ivan-hc** [comment] 2024-07-27 14:10
in the meantime I've found that the issue is this function
```
			if curl --output /dev/null --silent --head --fail "$API_GITHUB_REPO" | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -i "x86_64" | head -1 1>/dev/null; then
				FILTER=' | grep -i "x86_64" '
			elif curl --output /dev/null --silent --head --fail "$API_GITHUB_REPO" | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -i "x64" | head -1 1>/dev/null; then
				FILTER=' | grep -i "x64" '
			elif curl --output /dev/null --silent --head --fail "$API_GITHUB_REPO" | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -i "amd64" | head -1 1>/dev/null; then
				FILTER=' | grep -i "amd64" '
			else
				FILTER=' | grep -vi "i386\\|i686\\|aarch64\\|arm64\\|armv7l"'
			fi
```
this shoult detect "amd64" as an alternative in case the keyword "x86_64" does not exists

I need to fix this

**Comment by ivan-hc** [comment] 2024-07-27 14:22
`grep -e` seems to be the solution

**Closed** 2024-07-27 14:35 UTC

**Comment by ivan-hc** [comment] 2024-07-27 14:39
Solved, now the function is smaller
```
		if [ "$arch" == "x86_64" ]; then
			if curl --output /dev/null --silent --head --fail "$API_GITHUB_REPO" | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -ie "x86_64\|x64\|amd64" | head -1 1>/dev/null; then
				FILTER=' | grep -ie "x86_64\\|x64\\|amd64" '
			else
				FILTER=' | grep -vi "i386\\|i686\\|aarch64\\|arm64\\|armv7l"'
			fi
		elif [ "$arch" == "i686" ]; then
			FILTER=' | grep -ie "i386\\|i686\\|i586\\|i486" '
		elif [ "$arch" == "aarch64" ]; then
			FILTER=' | grep -ie "aarch64\\|arm64" '
		fi
```
"$FILTER" is ment to be added in the "$version" variable of the installation script.

I've tested with both
```
am -e https://github.com/music-assistant/companion music-assistant
```
that contains "amd64" and
```
am -e https://github.com/ivan-hc/Anydesk-appimage anydes
```
that contains "x86_64", and worked
