### ISSUE TITLE
Tracking list of Archived (Repo Read Only, No longer Maintained) Packages

### ISSUE THREAD

**Issue by Azathothas** [ivan-hc/AM#971] opened 2024-09-28 18:48 UTC
**Note**: This was generated automatically, and thus has a high chance that some of these might be false positives.
**Script**: https://paste.ajam.dev/p/zMcPxo

- https://github.com/5afe/safe-react
- https://github.com/ad-oliviero/uwufetch
- https://github.com/AKASHAorg/Community
- https://github.com/akuru-io/fontlet-explorer
- https://github.com/alephium/desktop-wallet
- https://github.com/alexcroox/jira-timer-menubar
- https://github.com/AlMcKinlay/McPodcast
- https://github.com/amoffat/supertag
- https://github.com/anatasluo/ant
- https://github.com/anupam-git/paper
- https://github.com/appium/appium-desktop
- https://github.com/AppOutlet/AppOutlet
- https://github.com/ArchGPT/insomnium
- https://github.com/ArkEcosystem/desktop-wallet
- https://github.com/AUCOHL/Malice
- https://github.com/bguyl/x-loc
- https://github.com/bloomrpc/bloomrpc
- https://github.com/BlueBrain/RTNeuron
- https://github.com/bodhiproject/bodhi-app
- https://github.com/bunqCommunity/bunqDesktop
- https://github.com/burtonator/polar-app-public
- https://github.com/CCI-Tools/cate-desktop
- https://github.com/cedoor/mindmapp
- https://github.com/cedoor/scraper
- https://github.com/cennznet/cennz-node-release
- https://github.com/ciderapp/cider-releases
- https://github.com/CircuitMess/CircuitBlocks
- https://github.com/cjdenio/playbox
- https://github.com/clipr/clipr
- https://github.com/CoatiSoftware/Sourcetrail
- https://github.com/ColinDuquesnoy/MellowPlayer
- https://github.com/crow-translate/crow-translate
- https://github.com/cutls/TheDesk
- https://github.com/dangeredwolf/ModernDeck
- https://github.com/darteil/POELadder
- https://github.com/davegallant/pocketcasts-electron
- https://github.com/Davis-Software/swc_mclauncher_old
- https://github.com/delirvfx/Delir
- https://github.com/denysdovhan/inboxer
- https://github.com/dineug/vuerd-electron
- https://github.com/DokiDokiModManager/Mod-Manager
- https://github.com/easyops-cn/console-workbench
- https://github.com/egoist/devdocs-desktop
- https://github.com/el3um4s/vue-calc
- https://github.com/eNkru/electron-xiami
- https://github.com/eNV25/freezer-releases
- https://github.com/EtherealEngine/ir-engine-launcher
- https://github.com/expo/xde
- https://github.com/foucdeg/x-plane-map-electron
- https://github.com/GeovaneSchmitz/tweakSophia
- https://github.com/GitSquared/edex-ui
- https://github.com/GooBox/file-share-desktop
- https://github.com/harshkhandeparkar/rainbow-board
- https://github.com/haxzie/instagram-live-streamer
- https://github.com/hello-efficiency-inc/raven-reader
- https://github.com/hello-efficiency-inc/ridereceipts
- https://github.com/holochain/n3h
- https://github.com/hugetiny/Hapee
- https://github.com/hyperspacedev/hyperspace-classic
- https://github.com/imfing/pile
- https://github.com/improbable-eng/Dragoman
- https://github.com/intiface/intiface-desktop
- https://github.com/iotaledger/trinity-wallet
- https://github.com/irccloud/irccloud-desktop
- https://github.com/ivan-hc/Arch-Deployer
- https://github.com/Janglee123/eplee
- https://github.com/jeffvli/sonixd
- https://github.com/jonathontoon/tweet-tray
- https://github.com/jscad/jscad-desktop
- https://github.com/jukben/keyboardio-led-custom-palette
- https://github.com/kremalicious/blowfish
- https://github.com/kuronekouwu/FishTerm
- https://github.com/l3laze/ReliefValve
- https://github.com/Lateralus138/bench-cli
- https://github.com/lauthieb/code-notes
- https://github.com/LazyT/rrcc
- https://github.com/LedgerHQ/ledger-live-desktop
- https://github.com/LiamRiddell/NoteMaster
- https://github.com/lightninglabs/lightning-app
- https://github.com/LightouchDev/MasterVyrn
- https://github.com/lighttransport/gltf-insight
- https://github.com/LINCnil/pia-app
- https://github.com/lluisrojass/tumblr-scraper
- https://github.com/LN-Zap/zap-desktop
- https://github.com/Lunarequest/NightPDF
- https://github.com/lxndr/impact
- https://github.com/Mainframe-Archive/onyx
- https://github.com/martinribelotta/launcher
- https://github.com/matthew-matvei/freeman
- https://github.com/mccxiv/tc
- https://github.com/migmartri/slacktronic
- https://github.com/mike-engel/Barnacal
- https://github.com/mr-islam/qawl
- https://github.com/nashaofu/dingtalk
- https://github.com/neuro-sys/tumblr-likes-downloader
- https://github.com/NyaomiDEV/Sunamu
- https://github.com/openethereum/fether
- https://github.com/OzymandiasTheGreat/Joy2DroidX-server
- https://github.com/pathephone/pathephone-desktop
- https://github.com/pm98zz-c/tT
- https://github.com/Pong420/Comic-Reader
- https://github.com/Pong420/google-tasks-desktop
- https://github.com/ProtocolONE/cord.launcher
- https://github.com/quanglam2807/singlebox-legacy
- https://github.com/radiium/turntable
- https://github.com/radixdlt/desktop-wallet
- https://github.com/railsware/upterm
- https://github.com/ridaamirini/ImapSyncClient
- https://github.com/ruralad/notedown
- https://github.com/samuelmeuli/mini-diary
- https://github.com/SandwichFox/MBCord
- https://github.com/sentinel-official/desktop-client
- https://github.com/shadowsocks/shadowsocks-qt5
- https://github.com/SimonBrandner/TaskizerDesktop
- https://github.com/smallhadroncollider/taskell
- https://github.com/software-challenge/gui-electron
- https://github.com/srevinsaju/guiscrcpy
- https://github.com/ssbc/patchwork
- https://github.com/stoplightio/desktop
- https://github.com/tenacityteam/saucedacity
- https://github.com/thecoder75/liveme-pro-tools
- https://github.com/TheGoddessInari/hamsket
- https://github.com/TheMarlboroMan/pigs-n-cows
- https://github.com/trazyn/weweChat
- https://github.com/trufflesuite/ganache-ui
- https://github.com/uhlibraries-digital/carpenters
- https://github.com/ujiro99/RedmineTimeTracker
- https://github.com/unofficial-protonmail-desktop/application
- https://github.com/vechain/thor-sync.electron
- https://github.com/vterm/vterm
- https://github.com/Wallby/file-to-c
- https://github.com/webcatalog/translatium-legacy
- https://github.com/webrecorder/webrecorder-desktop
- https://github.com/wexond/browser-base
- https://github.com/yafp/media-dupes
- https://github.com/yafp/ttth
- https://github.com/zenghongtu/Mob
- https://github.com/ZeroX-DG/SnippetStore
- https://github.com/Zerx0r/Kage
- https://github.com/ZeusWPI/MOZAIC
- https://github.com/zzzgydi/clash-verge

**Comment by ivan-hc** [comment] 2024-09-28 19:01
duplicate of https://github.com/ivan-hc/AM/issues/970

**Closed** 2024-09-28 19:00 UTC
