### ISSUE TITLE
Error when using --launcher in Kubuntu 24.04 

### ISSUE THREAD

**Issue by therealdudeshady** [ivan-hc/AM#534] opened 2024-05-01 07:53 UTC
Getting this error when using --launcher option with already downloaded appimage

/opt/am/modules/launcher.am: line 88: _patch_bashrc_and_profile: command not found
Do you want to customize the name of a symbolic link (Y) or let me choose (n)?

After putting a custom name, it exists and nothing happens

Specifically Cura
UltiMaker-Cura-5.7.1-linux-X64.AppImage

**Comment by Samueru-sama** [comment] 2024-05-01 08:30
I can't reproduce the issue here, however it is odd you have that `/opt/am/modules/launcher.am: line 88: _patch_bashrc_and_profile: command not found` error. Please run `am -u` to rule out an issue there. 

![image](https://github.com/ivan-hc/AM/assets/36420837/1837c919-584d-4917-91f3-b5bf9b769446)

However I have noticed that the `UltiMaker-Cura-5.7.1-linux-X64.AppImage.desktop` file does not show in my list of applications, that is because the `.desktop` is missing the `Name=...` string. That's odd because I just did an --appimage-extract and the the `com.ultimaker.cura.desktop` file does have a valid Name= string.

**Comment by therealdudeshady** [comment] 2024-05-01 08:44
Ah, thank you for such a quick reply!  Figured it was an odd error.  

I tried doing `am -u cura` but get the following error

"AM" CANNOT MANAGE UPDATES FOR "CURA"

**Comment by Samueru-sama** [comment] 2024-05-01 08:45
> Ah, thank you for such a quick reply! Figured it was an odd error.
> 
> I tried doing `am -u cura` but get the following error
> 
> "AM" CANNOT MANAGE UPDATES FOR "CURA"

Sorry my bad, the command is `am -i cura` am -u updates the program instead (which isn't installed and that is why you have the error).

**Comment by therealdudeshady** [comment] 2024-05-01 08:47
Absolute legend.  That did it, thank you so much.  Canonical should be paying out for this not being included in Ubuntu (or Kubuntu in my case)

**Comment by Samueru-sama** [comment] 2024-05-01 09:13
Alright @ivan-hc I think the launcher module needs a whole rework lol. 

I just added a `exit 0` before `rm -R -f ./squashfs-root` in the launcher.am module and checked inside ./squashfs-root and there is a fully valid .desktop file right in the first level of squashfs-root. 

```
[Desktop Entry]
X-AppImage-Arch=x86_64
X-AppImage-Version=5.7.1
X-AppImage-Name=UltiMaker Cura
Name=UltiMaker Cura
Exec=UltiMaker-Cura
Icon=cura-icon.png
Type=Application
Terminal=false
Categories=Utility;
Comment=
```

However the `.desktop` that gets installed in `$XDG_DATA_HOME/applications/AppImages` instead looks like this: 

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
StartupNotify=true
Exec=/home/samuel/UltiMaker-Cura-5.7.1-linux-X64.AppImage %U
X-AppImage-Name=UltiMaker Cura
Categories=Utility;
Comment=
Icon=cura-icon.png
```

With a missing `Name=` which prevents it from working. I also noticed that there are other .desktop files inside `squashfs-root/usr/share/applications` from other apps inside the appimage, so it may be that confuses the module I don't know.

**Comment by ivan-hc** [comment] 2024-05-01 22:41
@Samueru-sama to solve the Name entry issue its enough to add ^ in grep
```
cat ./squashfs-root/*.desktop | grep "^Name=" | head -1 >> ./"$appimage".desktop
```
but I still can't see the launcher, strange.

**Comment by ivan-hc** [comment] 2024-05-01 23:23
OK, just seen that I had to logout to see the launcher and icon.

The above commits in "dev" will definitely fix this issue.

**Comment by ivan-hc** [comment] 2024-05-03 00:54
The new launcher.am module for the option --launcher that fixes this issue has been merged right now. Have fun.

**Closed by ivan-hc** 2024-05-03 00:54 UTC
