### ISSUE TITLE
Update scrcpy-appimage

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#625] opened 2024-06-04 16:57 UTC
This is a fork with the latest version.
https://github.com/ardevd/scrcpy-appimage

**Comment by Samueru-sama** [comment] 2024-06-04 17:05
I have a bit of mixed feeling about this, srevinsaju is not inactive and I think we should ask him first. 

I don't know what @ivan-hc thinks though. 

Also @GeoBoi254 the terminal file managers were ready since I left the comment, only that the changes were merged to dev and haven't been added to main as another PR is being worked on.

**Comment by GeoBoi254** [comment] 2024-06-04 17:21
@Samueru-sama thanks for the PR on my last issue. 

This was just a suggestion since the project hasn't been updated in a while.

**Comment by Samueru-sama** [comment] 2024-06-04 17:27
> @Samueru-sama thanks for the PR on my last issue.
> 
> This was just a suggestion since the project hasn't been updated in a while.

No, don't say it is a suggestion, I understand this is a problem for you as you want to use the latest version. 

It is just that the person that kept the original appimage is a somebody that is still active and has made lots of contribution to appimages, I think we should ask them first if they are going to keep that project updated, else we will replace them with said fork.

**Comment by ivan-hc** [comment] 2024-06-04 17:42
If the maintainer agrees to maintain an official Appimage, so be it. Ask him, and show him the fork, asking him what he thinks.

On the contrary, I myself asked the maintainers of Bottles, Handbrake, MPV... all unfavorable. So I did my own thing and created the AppImages for them.

For now only GIMP seems to be inclined to release an official version, and when that is, I will update the script to distribute theirs. But not now. It is early.

So, should you refuse, I will gladly accept this unofficial version.

**Comment by Samueru-sama** [comment] 2024-06-04 17:47
@GeoBoi254 In the meantime you can use the `--launcher` option to integrate said appimage locally btw.

And if the fork hasn't changed much, you can edit the AM-updater script from the original appimages and replace the github url for the one of the work, and it will pull and keep up to date said fork btw

@ivan-hc So you think I should ask them if they will keep the appimage up to do? Or should be go ahead and replace it for the fork? 

Neither appimage is official, but the original is from somebody known to make this kind of stuff and also the creator of zap, so it kinda makes more "officialer" than the other 😅

Btw I said I because I have no problem going and opening and issue in the repo asking this before dropping it for the fork.

**Comment by ivan-hc** [comment] 2024-06-04 17:56
Amen. If the original authors want to complain, I will grant their request. To get feedback from them, "AM" needs to become popular and be widely used... I can already see Google and Microsoft asking me to remove Chrome and Edge Appimages :smile:

**Comment by Samueru-sama** [comment] 2024-06-04 18:04
> Amen. If the original authors want to complain, I will grant their request. To get feedback from them, "AM" needs to become popular and be widely used... I can already see Google and Microsoft asking me to remove Chrome and Edge Appimages 😄

Done, hopefully they answer soon.

**Comment by ivan-hc** [comment] 2024-06-05 00:43
the author of Zap was one of the first to inspire me to create "AppMan" and "AM". I would really like to suggest that he update his AppImages to Type3, he has created many... above all Brave and Firefox.

It would be a shame to replace his with a third party one... as @Samueru-sama says, he is still active after all.

But you could still create an "alter ego". See vlc and gimp:

![Istantanea_2024-06-05_02-43-10 png](https://github.com/ivan-hc/AM/assets/88724353/f4636117-60a5-4350-9b5d-604a3731ae07)

**Comment by ivan-hc** [comment] 2024-06-05 00:44
maybe a `scrcpy-ardevd`

**Comment by Samueru-sama** [comment] 2024-06-06 10:33
Alright the PR updating the appimage ready, it will be merged soon unless you want to wait a bit more @ivan-hc 

Btw I want to ask the librewolf guys to update their appimage to use the fuse3 compatible appimagetool, I even saw their build script and it is very easy to change it to use Go appimagetool: https://gitlab.com/librewolf-community/browser/appimage/-/blob/master/build_appimage.sh?ref_type=heads#L12

The problem is that I can't contact them because gitlab is asking for my payment information 😫 I don't know if you can do it for me please.

**Comment by ivan-hc** [comment] 2024-06-06 11:05
I had a contact with the librewolf team, I need to check it out... its because of me that they have a direct link to the appimage package

**Closed** 2024-06-06 11:06 UTC
